package sys.model;
// Generated 07-ago-2017 10:34:14 by Hibernate Tools 4.3.1



/**
 * Contribuyente generated by hbm2java
 */
public class Contribuyente  implements java.io.Serializable {


     private String id;
     private String ruc;
     private String razonSocial;
     private String nomComercial;
     private String estado;
     private String clase;
     private String inicioAct;
     private String fecActualizacion;
     private String fecSuspension;
     private String reinicioAct;
     private String obligado;
     private String tipoCont;
     private String numEstab;
     private String nomFantasia;
     private String calle;
     private String numCalle;
     private String interseccion;
     private String estadoEst;
     private String provincia;
     private String canton;
     private String parroquia;
     private String codigoCiiu;
     private String actividadEco;

    public Contribuyente() {
    }

	
    public Contribuyente(String id) {
        this.id = id;
    }
    public Contribuyente(String id, String ruc, String razonSocial, String nomComercial, String estado, String clase, String inicioAct, String fecActualizacion, String fecSuspension, String reinicioAct, String obligado, String tipoCont, String numEstab, String nomFantasia, String calle, String numCalle, String interseccion, String estadoEst, String provincia, String canton, String parroquia, String codigoCiiu, String actividadEco) {
       this.id = id;
       this.ruc = ruc;
       this.razonSocial = razonSocial;
       this.nomComercial = nomComercial;
       this.estado = estado;
       this.clase = clase;
       this.inicioAct = inicioAct;
       this.fecActualizacion = fecActualizacion;
       this.fecSuspension = fecSuspension;
       this.reinicioAct = reinicioAct;
       this.obligado = obligado;
       this.tipoCont = tipoCont;
       this.numEstab = numEstab;
       this.nomFantasia = nomFantasia;
       this.calle = calle;
       this.numCalle = numCalle;
       this.interseccion = interseccion;
       this.estadoEst = estadoEst;
       this.provincia = provincia;
       this.canton = canton;
       this.parroquia = parroquia;
       this.codigoCiiu = codigoCiiu;
       this.actividadEco = actividadEco;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getNomComercial() {
        return this.nomComercial;
    }
    
    public void setNomComercial(String nomComercial) {
        this.nomComercial = nomComercial;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getClase() {
        return this.clase;
    }
    
    public void setClase(String clase) {
        this.clase = clase;
    }
    public String getInicioAct() {
        return this.inicioAct;
    }
    
    public void setInicioAct(String inicioAct) {
        this.inicioAct = inicioAct;
    }
    public String getFecActualizacion() {
        return this.fecActualizacion;
    }
    
    public void setFecActualizacion(String fecActualizacion) {
        this.fecActualizacion = fecActualizacion;
    }
    public String getFecSuspension() {
        return this.fecSuspension;
    }
    
    public void setFecSuspension(String fecSuspension) {
        this.fecSuspension = fecSuspension;
    }
    public String getReinicioAct() {
        return this.reinicioAct;
    }
    
    public void setReinicioAct(String reinicioAct) {
        this.reinicioAct = reinicioAct;
    }
    public String getObligado() {
        return this.obligado;
    }
    
    public void setObligado(String obligado) {
        this.obligado = obligado;
    }
    public String getTipoCont() {
        return this.tipoCont;
    }
    
    public void setTipoCont(String tipoCont) {
        this.tipoCont = tipoCont;
    }
    public String getNumEstab() {
        return this.numEstab;
    }
    
    public void setNumEstab(String numEstab) {
        this.numEstab = numEstab;
    }
    public String getNomFantasia() {
        return this.nomFantasia;
    }
    
    public void setNomFantasia(String nomFantasia) {
        this.nomFantasia = nomFantasia;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumCalle() {
        return this.numCalle;
    }
    
    public void setNumCalle(String numCalle) {
        this.numCalle = numCalle;
    }
    public String getInterseccion() {
        return this.interseccion;
    }
    
    public void setInterseccion(String interseccion) {
        this.interseccion = interseccion;
    }
    public String getEstadoEst() {
        return this.estadoEst;
    }
    
    public void setEstadoEst(String estadoEst) {
        this.estadoEst = estadoEst;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }
    public String getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(String parroquia) {
        this.parroquia = parroquia;
    }
    public String getCodigoCiiu() {
        return this.codigoCiiu;
    }
    
    public void setCodigoCiiu(String codigoCiiu) {
        this.codigoCiiu = codigoCiiu;
    }
    public String getActividadEco() {
        return this.actividadEco;
    }
    
    public void setActividadEco(String actividadEco) {
        this.actividadEco = actividadEco;
    }




}


